import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();
const date = (value:string)=>new Date(`${value}T12:00:00.000Z`);

async function main(){
  const org=await db.organisation.findFirstOrThrow();const admin=await db.user.findFirstOrThrow({where:{organisationId:org.id,role:"ADMIN"}});
  const legacyDrafts=await db.programme.findMany({where:{organisationId:org.id,code:{not:"GEE-2026"}},select:{id:true,name:true}});
  for(const item of legacyDrafts.filter(item=>/(create|generate|girl.?child education|girlchild education)/i.test(item.name)))await db.programme.update({where:{id:item.id},data:{status:"ARCHIVED"}});
  const programme=await db.programme.upsert({where:{code:"GEE-2026"},update:{},create:{organisationId:org.id,name:"Girls’ Education and Empowerment Programme",code:"GEE-2026",description:"Supports adolescent girls to enroll in, attend and complete secondary school through mentoring, family engagement and school-level support.",problemStatement:"Girls in underserved communities face attendance, safety, affordability and transition barriers that increase secondary-school dropout.",geography:"Dhar district, Madhya Pradesh",targetPopulation:"600 adolescent girls in grades 8–12",startDate:date("2026-04-01"),endDate:date("2028-03-31"),budget:16000000,objectives:"Increase girls’ regular attendance, grade transition and secondary-school retention.",activities:"Mentoring clubs, attendance follow-up, scholarships, family engagement and school safeguarding support.",outputs:"Girls enrolled and mentored; caregivers engaged; attendance barriers resolved.",outcomes:"More girls attend at least 80% of classes and transition to the next grade.",impact:"Girls complete secondary education with greater agency and opportunity.",assumptions:"Families support continued education; schools provide safe and inclusive learning environments.",risks:"Seasonal migration, safety concerns and household financial shocks may interrupt attendance.",partners:"District Education Department; community school committees"}});
  async function funder(name:string,type:string){return await db.funder.findFirst({where:{organisationId:org.id,name}})??db.funder.create({data:{organisationId:org.id,name,type,website:"",primaryContact:"Demo Relationship Manager",contactEmail:"demo@example.org",notes:"Girls’ secondary education partner."}})}
  const [educationFunder,csrFunder]=await Promise.all([funder("Shiksha Equity Foundation","FOUNDATION"),funder("Bright Futures CSR Alliance","CORPORATE_CSR")]);
  const [brsr,csr2]=await Promise.all([db.framework.findUniqueOrThrow({where:{name:"BRSR"},include:{requirements:true}}),db.framework.findUniqueOrThrow({where:{name:"CSR-2"},include:{requirements:true}})]);
  async function grant(name:string,funderId:string,frameworkId:string,amount:number,next:string){return await db.grant.findFirst({where:{name,programmeId:programme.id}})??db.grant.create({data:{name,amount,currency:"INR",startDate:date("2026-04-01"),endDate:date("2028-03-31"),reportingFrequency:"Quarterly",nextReportDate:date(next),programmeId:programme.id,funderId,frameworkId,requirements:"Report attendance, retention, beneficiary reach, disaggregation, safeguarding and corrective action."}})}
  const [grantB,grantC]=await Promise.all([grant("Girls’ Secondary Retention Grant",educationFunder.id,brsr.id,10000000,"2026-09-20"),grant("Safe Schools CSR Partnership",csrFunder.id,csr2.id,6000000,"2026-10-15")]);
  async function node(name:string,level:string,parentId:string|null){return await db.taxonomyNode.findFirst({where:{name,level,parentId}})??db.taxonomyNode.create({data:{name,level,parentId}})}
  const sector=await node("Education","SECTOR",null);const sub=await node("Girls’ Education","SUB_SECTOR",sector.id);const focus=await node("Secondary-School Retention","SUB_SUB_SECTOR",sub.id);
  for(const taxonomyNodeId of [sector.id,sub.id,focus.id])await db.programmeTaxonomy.upsert({where:{programmeId_taxonomyNodeId:{programmeId:programme.id,taxonomyNodeId}},update:{confidence:1},create:{programmeId:programme.id,taxonomyNodeId,confidence:1}});
  if(!await db.theoryOfChangeNode.findFirst({where:{programmeId:programme.id}}))await db.theoryOfChangeNode.createMany({data:[["INPUT","Mentors, scholarships and safe-school partners"],["ACTIVITY","Deliver mentoring and attendance follow-up"],["OUTPUT","Girls receive sustained education support"],["OUTCOME","Girls attend regularly and transition grades"],["IMPACT","Girls complete secondary education"]].map(([level,title],i)=>({programmeId:programme.id,level,title,description:title,assumptions:"Schools and families sustain safe participation.",sortOrder:i+1}))});
  const specs=[
    {name:"Girls attending at least 80% of scheduled classes",definition:"Percentage of enrolled girls whose attendance rate is at least 80% in the reporting period.",target:80,actual:67,status:"AT_RISK",grantId:grantB.id,requirementId:brsr.requirements[0]?.id,key:"attendance_threshold",question:"Did the enrolled girl attend at least 80% of scheduled school days?",type:"BOOLEAN",role:"NUMERATOR"},
    {name:"Girls supported through mentoring",definition:"Unique enrolled girls completing at least one mentoring session in the period.",target:3,actual:3,status:"ON_TRACK",grantId:grantC.id,requirementId:csr2.requirements[0]?.id,key:"mentoring_received",question:"Did the student complete a programme mentoring session?",type:"BOOLEAN",role:"SUPPORTING"},
    {name:"Girls transitioning to the next grade",definition:"Percentage of eligible girls progressing to the next grade at year end.",target:85,actual:72,status:"AT_RISK",grantId:grantB.id,requirementId:brsr.requirements[0]?.id,key:"grade_transition",question:"Did the student transition to the next grade?",type:"BOOLEAN",role:"NUMERATOR"},
  ];
  const indicators=[];
  for(const spec of specs){let indicator=await db.indicator.findFirst({where:{programmeId:programme.id,name:spec.name}});indicator??=await db.indicator.create({data:{programmeId:programme.id,grantId:spec.grantId,requirementId:spec.requirementId,name:spec.name,definition:spec.definition,resultLevel:"OUTCOME",formula:"Eligible numerator ÷ eligible denominator × 100",calculationType:spec.name.includes("mentoring")?"COUNT":"PERCENTAGE",numerator:"Girls meeting the indicator condition",denominator:"All eligible enrolled girls",unit:spec.name.includes("mentoring")?"girls":"%",baseline:0,target:spec.target,actual:spec.actual,status:spec.status,frequency:"Quarterly",dataSource:"UniCollector and school attendance records",collectionMethod:"Structured digital form",responsiblePerson:"Rohan Das",disaggregation:"Grade, location, disability",objective:programme.objectives,qualityRules:"Required response; unique student-period; school register verification",completeness:100,lastUpdated:date("2026-08-10")}});const field=await db.dataField.upsert({where:{programmeId_key:{programmeId:programme.id,key:spec.key}},update:{},create:{programmeId:programme.id,indicatorId:indicator.id,key:spec.key,label:spec.name,definition:spec.definition,question:spec.question,type:spec.type,required:true,unit:indicator.unit,validationRule:"Yes or No response required",collectionFrequency:"Quarterly",calculationRole:spec.role,disaggregation:"Grade, school and disability",dataSource:"UniCollector"}});indicators.push({indicator,field});}
  for(let i=0;i<3;i++){const beneficiaryId=`GEE-00${i+1}`;if(await db.submission.findFirst({where:{programmeId:programme.id,beneficiaryId,reportingPeriod:"2026 Q3"}}))continue;const submission=await db.submission.create({data:{programmeId:programme.id,grantId:grantB.id,submittedById:admin.id,submittedAt:date(`2026-08-${String(8+i).padStart(2,"0")}`),reportingPeriod:"2026 Q3",location:["Badnawar","Dhar","Sardarpur"][i],beneficiaryId,gender:"Girl",ageGroup:"Under 18",disability:"No",consent:true,source:"UniCollector",validationStatus:"VALID"}});await db.observation.create({data:{submissionId:submission.id,indicatorId:indicators[0].indicator.id,dataFieldId:indicators[0].field.id,numericValue:i<2?100:0,textValue:i<2?"yes":"no"}})}
  if(!await db.alert.findFirst({where:{programmeId:programme.id,type:"INDICATOR_AT_RISK"}}))await db.alert.create({data:{programmeId:programme.id,grantId:grantB.id,indicatorId:indicators[0].indicator.id,type:"INDICATOR_AT_RISK",severity:"MEDIUM",reason:"Girls attending at least 80% of classes is 13 percentage points below target.",owner:"Rohan Das",status:"OPEN",triggeredAt:date("2026-08-10")}});
  if(!await db.report.findFirst({where:{programmeId:programme.id,period:"2026 Q3"}}))await db.report.create({data:{title:"Girls’ Education and Empowerment Programme — 2026 Q3 Progress Report",programmeId:programme.id,grantId:grantB.id,period:"2026 Q3",type:"Funder progress report",comparisonPeriod:"2026 Q2",frameworkName:"BRSR",executiveSummary:"Saved monitoring evidence shows mentoring reach on track while regular attendance needs focused follow-up.",achievements:"Three girls have completed documented mentoring in the current demonstration dataset.",risks:"Regular attendance remains below target; follow up seasonal and household barriers.",lessons:"School-level attendance review enables earlier, more targeted support.",status:"DRAFT"}});
  console.log("Girls’ education demo story is present without deleting existing data.");
}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>db.$disconnect());
